apiVersion: v1
kind: Service
metadata:
  labels:
    run: myapi
  name: myapi-lb
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: myapi
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
